### ISSUE TITLE
Error in subtype constraint for physical types

### ISSUE THREAD

**Issue by Paebbels** [ghdl/ghdl#918]
**Description**
I created a physical type `voltage` for an experimental simulation. When using physical types in ports with a constraint, it causes a crash.

**Expected behavior**
Display an error message or don't crash.

**Context**
```
$ $GHDL -a --std=08 reproducer.vhdl
connect_scalar: cannot handle IIR_KIND_PHYSICAL_SUBTYPE_DEFINITION (reproducer.vhdl:4:38)

******************** GHDL Bug occurred ***************************
Please report this bug on https://github.com/ghdl/ghdl/issues
GHDL release: 0.37-dev (v0.36-940-gf0c54c66-dirty) [Dunoon edition]
Compiled with GNAT Version: 9.2.0
Target: x86_64-w64-mingw32
C:\Projects\Bosch-Athena\_MHA Board\BoardSim\temp\Bug\
Command line:
C:\Tools\GHDL\0.37-dev-mingw64-llvm80\bin\ghdl1-llvm.exe --std=08 -PC:\Tools\GHDL\0.37-dev-mingw64-llvm80\lib/ghdl\ieee\v08\ -PC:\Tools\GHDL\0.37-dev-mingw64-llvm80\lib/ghdl\ -c -o reproducer.o reproducer.vhdl
Exception TYPES.INTERNAL_ERROR raised
Exception information:
raised TYPES.INTERNAL_ERROR : vhdl-errors.adb:32
Call stack traceback locations:
0x4932fd 0x5a619d 0x5a43fc 0x5a6ed5 0x5a86d6 0x5a913e 0x59fd3c 0x59b0a6 0x59b83a 0x61e907 0x568c5b 0x624ea4 0x6265c3 0x627fd5 0x40264d 0x40138a 0x4014b9 0x7ff810307bd2 0x7ff8122ace6f
******************************************************************
C:\Tools\GHDL\0.37-dev-mingw64-llvm80\bin\ghdl.exe: compilation error
```

Please paste the `GHDL Bug occurred` log block here. Also, provide the following information:

- OS: MinGW64 (Windows 10, 64-bit)
- Origin:
  - [ ] Package manager. Repo:
  - [ ] Released binaries. Tarball:
  - [x] Built from sources. Commit SHA: f0c54c66df07bbe8da99ec8157d87708bfd8886f

**Additional context**
MinGW64 build with llvm 8.0 backend.

The error is caused when analyzing the top-level entity, while it's binding the instantiated entity.

**How to reproduce?**
```vhdl
#>> ent.vhd
package power is
  type voltage is range integer'low to integer'high units
    uV;
    mV = 1000 uV;
     V = 1000 mV;
    kV = 1000  V;
  end units;
end package;

use work.power.all;

entity LTC is
  generic (
    V_MIN : voltage := 0 V;
    V_MAX : voltage := voltage'high
  );
  port (
    Vin  : in  voltage range 0 V to 15 V;
    Vout : out voltage range V_MIN to V_MAX
  );
end entity;

architecture ic of LTC is
begin
  Vout <= Vin * 0.95;
end architecture;

use work.power.all;

entity board is
  port (
    Vin  : in  voltage;
    Vout : out voltage
  );
end entity;

architecture ic of board is
begin
  U1: entity work.LTC
    port map (
      Vin  => 2.5 V,
      Vout => open
    );
end architecture;

#>> sim.sh
ghdl -a ent.vhd
ghdl --elab-run ent

#>> run.sh
docker run --rm -tv /$(pwd):/src:z -w //src ghdl/ghdl:buster-mcode sh -c ./sim.sh

#>> end
```

**Checklist**
Before submitting your issue, please review the following checklist:

- [x] Add `GHDL Bug occurred` log block
- [x] Add a MWE
- [x] Try the latest version
