### ISSUE TITLE
grt fails to build with GCC/GNAT 11

### ISSUE THREAD

**Issue by sharkcz** [ghdl/ghdl#1652]
grt fails to build with latest gcc (GCC) 11.0.0 20210210 (Red Hat 11.0.0-0) in Fedora
````
...
gcc -c -I./ -I/builddir/build/BUILD/gcc-10.2.1-20200826/ghdl-llvm/./src/grt -I.. -gnatec/builddir/build/BUILD/gcc-10.2.1-20200826/ghdl-llvm/./src/grt/grt.adc -gnatdY -g -I- /builddir/build/BUILD/gcc-10.2.1-20200826/ghdl-llvm/src/grt/grt-signals.adb
grt-signals.adb:556:20: illegal attribute for discriminant-dependent component
gnatmake: "/builddir/build/BUILD/gcc-10.2.1-20200826/ghdl-llvm/src/grt/grt-signals.adb" compilation error
````
The offending line is https://github.com/ghdl/ghdl/blob/master/src/grt/grt-signals.adb#L556

**Comment by tgingold** [comment]
Does it work if you replaced `'Access` by `'Unrestricted_Access` ?

**Comment by sharkcz** [comment]
seems it doesn't
````
grt-signals.adb:556:37: no selector "Unrestricted_Access" for type "Driver_Type" defined at grt-signals.ads:76
````

**Comment by tgingold** [comment]
Did you put a dot before (instead of a single quote) ?
The error message is not expected.

**Comment by sharkcz** [comment]
yes, there was a dot
````
         if Sig.S.Drivers (I).Proc = Proc then
            return Sig.S.Drivers (I)'Unrestricted_Access;
         end if;
````
^^ compiles
